apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-service-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: greeter-service
      environment: staging
  template:
    metadata:
      labels:
        app: greeter-service
        environment: staging
    spec:
      containers:
        - image: jdmcneal1/greeter-server@sha256:14bc7ffa918bf88f495b845a7e8f52211a60920750f55d40b7d1f83748b8a5f1
          imagePullPolicy: IfNotPresent
          name: greeter-server
          ports:
            - containerPort: 5000
